name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [ubuntu, windows, macos]
        include:
          - build: macos
            os: macos-latest
          - build: windows
            os: windows-latest
          - build: ubuntu
            os: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy -- -Dwarnings

  exe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install package
      run: cargo install --path .
    - name: Run base
      run: ilmn2ped test/test.tsv
    - name: Run with map (tsv)
      run: ilmn2ped test/test.tsv --map test/map.tsv
    - name: Run csvs
      run: ilmn2ped test/test.csv --map test/map.csv
    - name: Run alternative tsv + map csv
      run: ilmn2ped test/test2.tsv --map test/map.csv
