name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          build: [beta, stable, windows, macos]
          include:
            - build: macos
              os: macos-latest
            - build: windows
              os: windows-latest
            - build: stable
              os: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
